### ISSUE TITLE
Selfoss URL

### ISSUE THREAD

**Issue by n00b12345** [amaccuish/selfoss-fever#1]
Just a query regarding how to input the selfoss URL location in the index.php file on sever. 

My selfoss instance is located in https://localhost/selfoss

So, should I enter the URL in the index.php file as "/selfoss"? Or should it be something else?

Thanks for creating this plugin.

**Comment by amaccuish** [comment]
"/selfoss/" should be alright :) your webserver should be configured to route all urls below "/selfoss" to the "index.php" file of selfoss, so my script can access its api :)

**Comment by n00b12345** [comment]
@amaccuish I tried multiple times yesterday and today, changing various configurations as well. It doesn't authenticate :(

I tried with Unread and Fiery Feeds apps for iOS. 

I placed the selfoss-fever folder on my server. Changed index.php file to locate selfoss URL. And then tried to connect using https://(localhost)/selfoss-fever. 

It connects, but doesn't sync anything. I wish I could debug this. 

These are the errors in the Apache log:

`Invalid argument supplied for foreach() in ...`

`Undefined variable: feedsGroup in...`

**Comment by amaccuish** [comment]
Sorry for the delay, been super busy; I'll have a look into it over the next few days :)

**Comment by amaccuish** [comment]
Right, sorry been so busy. I assume you don't have any tags defined? Just add one of your feeds to a tag and I'll add in the required checks and upload in a bit :) Got anymore from those logs like line numbers?

**Comment by n00b12345** [comment]
Terribly sorry for the delay. I'll just test it and let you know. Thank you so much for the help. Really appreciate it.

**Comment by amaccuish** [comment]
Any luck?

**Comment by amaccuish** [comment]
Closing due to no reply
